In [1]:
import numpy as np
import pandas as pd

# Reading in Data

`data_3_0.txt` is a text file with features seperated by commas. `data_4_2.txt` is a text file with only staging variables, listed in the same order

In [2]:
data3 = pd.read_csv('data_3_0.txt',sep=',', header=0)
#need to convert the diff numbres into, three different categories

/opt/conda/envs/ml/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (16,24) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
data3

,Site recode ICD-O-3/WHO 2008,Sex,Summary stage 2000 (1998+),Grade,Lymph-vascular Invasion (2004+ varying by schema),"Race recode (W, B, AI, API)",Age recode with <1 year olds,Primary Site - labeled,Tumor Size Summary (2016+),CS tumor size (2004-2015),...,Total number of in situ/malignant tumors for patient,CS extension (2004-2015),Laterality,ER Status Recode Breast Cancer (1990+),PR Status Recode Breast Cancer (1990+),COD to site recode,SEER cause-specific death classification,SEER other cause of death classification,Survival months,Survival months flag
0,Breast,Female,In situ,Poorly differentiated; Grade III,Blank(s),Black,65-69 years,"C50.9-Breast, NOS",Blank(s),013,...,2,000,Left - origin of primary,Unknown,Unknown,Alive,Alive or dead of other cause,Alive or dead due to cancer,0000,Complete dates are available and there are 0 d...
1,Breast,Female,In situ,Moderately differentiated; Grade II,Blank(s),White,80-84 years,C50.4-Upper-outer quadrant of breast,Blank(s),027,...,3,000,Left - origin of primary,Positive,Positive,Alive,Alive or dead of other cause,Alive or dead due to cancer,0051,Complete dates are available and there are mor...
2,Breast,Female,In situ,Moderately differentiated; Grade II,Blank(s),Black,55-59 years,"C50.9-Breast, NOS",Blank(s),011,...,2,000,Left - origin of primary,Positive,Positive,Alive,Alive or dead of other cause,Alive or dead due to cancer,0052,Complete dates are available and there are mor...
3,Breast,Female,In situ,Unknown,Blank(s),White,65-69 years,"C50.9-Breast, NOS",Blank(s),004,...,3,000,Right - origin of primary,Positive,Positive,Alive,Alive or dead of other cause,Alive or dead due to cancer,0091,Complete dates are available and there are mor...
4,Breast,Female,In situ,Poorly differentiated; Grade III,Blank(s),White,45-49 years,C50.2-Upper-inner quadrant of breast,Blank(s),Blank(s),...,1,Blank(s),Right - origin of primary,Unknown,Unknown,Alive,Alive or dead of other cause,Alive or dead due to cancer,0191,Complete dates are available and there are mor...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327871,Breast,Female,Localized,Poorly differentiated; Grade III,Blank(s),White,60-64 years,"C50.9-Breast, NOS",Blank(s),007,...,2,100,Left - origin of primary,Positive,Negative,Other Cause of Death,Alive or dead of other cause,Dead (attributable to causes other than this c...,0091,Complete dates are available and there are mor...
1327872,Breast,Female,Localized,Well differentiated; Grade I,Blank(s),White,55-59 years,C50.2-Upper-inner quadrant of breast,Blank(s),020,...,1,100,Left - origin of primary,Positive,Negative,Alive,Alive or dead of other cause,Alive or dead due to cancer,0149,Complete dates are available and there are mor...
1327873,Breast,Female,Regional,Poorly differentiated; Grade III,Blank(s),White,60-64 years,C50.2-Upper-inner quadrant of breast,Blank(s),040,...,1,200,Right - origin of primary,Unknown,Unknown,State DC not available or state DC available b...,Dead (missing/unknown COD),Dead (missing/unknown COD),0030,Complete dates are available and there are mor...
1327874,Breast,Female,Regional,Poorly differentiated; Grade III,Blank(s),White,55-59 years,C50.8-Overlapping lesion of breast,Blank(s),035,...,1,100,Left - origin of primary,Positive,Positive,Alive,Alive or dead of other cause,Alive or dead due to cancer,0154,Complete dates are available and there are mor...
1327875,Breast,Female,Localized,Moderately differentiated; Grade II,Blank(s),White,70-74 years,C50.4-Upper-outer quadrant of breast,Blank(s),010,...,1,100,Left - origin of primary,Positive,Positive,Diseases of Heart,Alive or dead of other cause,Dead (attributable to causes other than this c...,0115,Complete dates are available and there are mor...

In [4]:
list(data3.columns)

['Site recode ICD-O-3/WHO 2008',
 'Sex',
 'Summary stage 2000 (1998+)',
 'Grade',
 'Lymph-vascular Invasion (2004+ varying by schema)',
 'Race recode (W, B, AI, API)',
 'Age recode with <1 year olds',
 'Primary Site - labeled',
 'Tumor Size Summary (2016+)',
 'CS tumor size (2004-2015)',
 'Reason no cancer-directed surgery',
 'Histologic Type ICD-O-3',
 'Behavior recode for analysis',
 'Behavior code ICD-O-3',
 'Regional nodes positive (1988+)',
 'Regional nodes examined (1988+)',
 'Total number of in situ/malignant tumors for patient',
 'CS extension (2004-2015)',
 'Laterality',
 'ER Status Recode Breast Cancer (1990+)',
 'PR Status Recode Breast Cancer (1990+)',
 'COD to site recode',
 'SEER cause-specific death classification',
 'SEER other cause of death classification',
 'Survival months',
 'Survival months flag']

In [5]:
data4 = pd.read_csv('data_4_2.txt',sep=',', header=0)

In [6]:
data4

,Breast - Adjusted AJCC 6th Stage (1988-2015),Breast - Adjusted AJCC 6th T (1988-2015),Breast - Adjusted AJCC 6th N (1988-2015),Breast - Adjusted AJCC 6th M (1988-2015),Behavior recode for analysis
0,0,Tis,N0,M0,In situ
1,0,Tis,N0,M0,In situ
2,0,Tis,N0,M0,In situ
3,0,Tis,N0,M0,In situ
4,0,Tis,N0,M0,In situ
...,...,...,...,...,...
1327871,I,T1b,N0,M0,Malignant
1327872,I,T1c,N0,M0,Malignant
1327873,IIB,T2,N1,M0,Malignant
1327874,IIIC,T2,N3,M0,Malignant
1327875,I,T1b,N0,M0,Malignant

In [7]:
list(data4.columns)

['Breast - Adjusted AJCC 6th Stage (1988-2015)',
 'Breast - Adjusted AJCC 6th T (1988-2015)',
 'Breast - Adjusted AJCC 6th N (1988-2015)',
 'Breast - Adjusted AJCC 6th M (1988-2015)',
 'Behavior recode for analysis']

In [8]:
data4 = data4.drop(columns='Behavior recode for analysis')

# Concat data3 and data4

In [9]:
data3 = pd.concat([data3, data4], axis=1)

In [10]:
list(data3.columns)

['Site recode ICD-O-3/WHO 2008',
 'Sex',
 'Summary stage 2000 (1998+)',
 'Grade',
 'Lymph-vascular Invasion (2004+ varying by schema)',
 'Race recode (W, B, AI, API)',
 'Age recode with <1 year olds',
 'Primary Site - labeled',
 'Tumor Size Summary (2016+)',
 'CS tumor size (2004-2015)',
 'Reason no cancer-directed surgery',
 'Histologic Type ICD-O-3',
 'Behavior recode for analysis',
 'Behavior code ICD-O-3',
 'Regional nodes positive (1988+)',
 'Regional nodes examined (1988+)',
 'Total number of in situ/malignant tumors for patient',
 'CS extension (2004-2015)',
 'Laterality',
 'ER Status Recode Breast Cancer (1990+)',
 'PR Status Recode Breast Cancer (1990+)',
 'COD to site recode',
 'SEER cause-specific death classification',
 'SEER other cause of death classification',
 'Survival months',
 'Survival months flag',
 'Breast - Adjusted AJCC 6th Stage (1988-2015)',
 'Breast - Adjusted AJCC 6th T (1988-2015)',
 'Breast - Adjusted AJCC 6th N (1988-2015)',
 'Breast - Adjusted AJCC 6th M (1988-2015)']

In [11]:
data3.shape

(1327876, 30)

In [12]:
data3['Sex'].value_counts()

Female    1318896
Male         8980
Name: Sex, dtype: int64

# Variable Specific Preprocessing

In [52]:
for name in data3.columns:
    print('\n'+name)
    print(data3[name].value_counts())

Site recode ICD-O-3/WHO 2008
Breast    1327876
Name: Site recode ICD-O-3/WHO 2008, dtype: int64

Sex
Female    1318896
Male         8980
Name: Sex, dtype: int64

Summary stage 2000 (1998+)
Localized           669337
Regional            318963
In situ             255703
Distant              58158
Unknown/unstaged     25715
Name: Summary stage 2000 (1998+), dtype: int64

Grade
Moderately differentiated; Grade II       506450
Poorly differentiated; Grade III          392618
Well differentiated; Grade I              244723
Unknown                                   156303
Undifferentiated; anaplastic; Grade IV     27782
Name: Grade, dtype: int64

Lymph-vascular Invasion (2004+ varying by schema)
Blank(s)    1327876
Name: Lymph-vascular Invasion (2004+ varying by schema), dtype: int64

Race recode (W, B, AI, API)
White                            1065269
Black                             141670
Asian or Pacific Islander         105440
Unknown                             8589
American Indian/Alaska Native       6908
Name: Race recode (W, B, AI, API), dtype: int64

Age recode with <1 year olds
60-64 years    168909
55-59 years    166301
65-69 years    161232
50-54 years    159674
45-49 years    137488
70-74 years    133537
75-79 years    108945
40-44 years     88800
80-84 years     77753
85+ years       64764
35-39 years     38347
30-34 years     15992
25-29 years      5085
20-24 years       935
15-19 years       100
10-14 years        11
05-09 years         2
01-04 years         1
Name: Age recode with <1 year olds, dtype: int64

Primary Site - labeled
C50.4-Upper-outer quadrant of breast    429181
C50.8-Overlapping lesion of breast      281484
C50.9-Breast, NOS                       225085
C50.2-Upper-inner quadrant of breast    138594
C50.5-Lower-outer quadrant of breast     90979
C50.1-Central portion of breast          74275
C50.3-Lower-inner quadrant of breast     72454
C50.0-Nipple                              8758
C50.6-Axillary tail of breast             7066
Name: Primary Site - labeled, dtype: int64

Tumor Size Summary (2016+)
Blank(s)    1160973
999           13898
015            8286
012            7271
010            6407
             ...
162               1
550               1
205               1
251               1
760               1
Name: Tumor Size Summary (2016+), Length: 230, dtype: int64

CS tumor size (2004-2015)
Blank(s)    431921
999          88667
015          51388
010          39758
012          35969
             ...
506              1
762              1
315              1
695              1
405              1
Name: CS tumor size (2004-2015), Length: 318, dtype: int64

Reason no cancer-directed surgery
Surgery performed                                                               1215193
Not recommended                                                                   72305
Recommended but not performed, unknown reason                                     11263
Recommended but not performed, patient refused                                     9233
Unknown; death certificate; or autopsy only (2003+)                                8018
Recommended, unknown if performed                                                  6961
Not recommended, contraindicated due to other cond; autopsy only (1973-2002)       4201
Not performed, patient died prior to recommended surgery                            702
Name: Reason no cancer-directed surgery, dtype: int64

Histologic Type ICD-O-3
8500    838273
8520    123197
8523     95921
8522     77815
8201     23652
         ...
8912         1
8350         1
8933         1
9581         1
8950         1
Name: Histologic Type ICD-O-3, Length: 176, dtype: int64

Behavior recode for analysis
Malignant    1072172
In situ       255704
Name: Behavior recode for analysis, dtype: int64

Behavior code ICD-O-3
Malignant    1072172
In situ       255704
Name: Behavior code ICD-O-3, dtype: int64

Regional nodes positive (1988+)
0     680184
98    327201
1     121394
2      48645
3      26215
       ...
70         1
63         1
59         1
88         1
87         1
Name: Regional nodes positive (1988+), Length: 80, dtype: int64

Regional nodes examined (1988+)
0     327201
1     182388
2     160203
3     112404
4      70271
       ...
80         1
73         1
83         1
71         1
82         1
Name: Regional nodes examined (1988+), Length: 88, dtype: int64

Total number of in situ/malignant tumors for patient
1          742240
2          255595
01         196416
3           55047
02          53194
4           10388
03          10245
5            1876
04           1864
6             454
05            336
7              75
06             51
8              39
07             18
Unknown        11
10              6
09              5
08              4
9               4
11              3
20              2
13              1
50              1
14              1
Name: Total number of in situ/malignant tumors for patient, dtype: int64

CS extension (2004-2015)
100         626796
Blank(s)    431921
000         175687
999          23408
200          21674
510           6283
300           5196
512           4772
400           3895
750           3569
710           3450
140           2269
950           2000
730           1918
580           1844
190           1827
520           1683
070           1496
130           1252
110            776
120            673
514            568
050            521
790            504
600            485
610            430
725            377
605            369
585            298
180            285
518            244
780            243
612            215
410            201
620            179
615            132
680            128
575            107
170             84
516             73
519             36
613              6
715              2
Name: CS extension (2004-2015), dtype: int64

Laterality
Left - origin of primary                                 668924
Right - origin of primary                                646073
Paired site, but no information concerning laterality     11076
Only one side - side unspecified                           1182
Bilateral, single primary                                   621
Name: Laterality, dtype: int64

ER Status Recode Breast Cancer (1990+)
Positive      932914
Negative      209444
Unknown       184086
Borderline      1432
Name: ER Status Recode Breast Cancer (1990+), dtype: int64

PR Status Recode Breast Cancer (1990+)
Positive      788091
Negative      330857
Unknown       204551
Borderline      4377
Name: PR Status Recode Breast Cancer (1990+), dtype: int64

COD to site recode
Alive                                                 990658
Breast                                                145332
Diseases of Heart                                      46478
Other Cause of Death                                   29333
Cerebrovascular Diseases                               11832
                                                       ...
Certain Conditions Originating in Perinatal Period         2
Penis                                                      2
Other Male Genital Organs                                  1
Syphilis                                                   1
Testis                                                     1
Name: COD to site recode, Length: 94, dtype: int64

SEER cause-specific death classification
Alive or dead of other cause             1164780
Dead (attributable to this cancer dx)     157487
Dead (missing/unknown COD)                  5598
N/A not seq 0-59                              11
Name: SEER cause-specific death classification, dtype: int64

SEER other cause of death classification
Alive or dead due to cancer                                1148135
Dead (attributable to causes other than this cancer dx)     174132
Dead (missing/unknown COD)                                    5598
N/A not seq 0-59                                                11
Name: SEER other cause of death classification, dtype: int64

Survival months
0000    15707
0001    12616
0002    12326
0004    12037
0006    11362
        ...
212       246
211       242
213       234
209       206
215       205
Name: Survival months, Length: 433, dtype: int64

Survival months flag
Complete dates are available and there are more than 0 days of survival      1109681
Incomplete dates are available and there cannot be zero days of follow-up     208819
Not calculated because a Death Certificate Only or Autopsy Only case            4929
Incomplete dates are available and there could be zero days of follow-up        2519
Complete dates are available and there are 0 days of survival                   1928
Name: Survival months flag, dtype: int64

Breast - Adjusted AJCC 6th Stage (1988-2015)
I            422842
0            226087
IIA          208302
Blank(s)     166903
IIB           90866
UNK Stage     57794
IIIA          56913
IV            45927
IIIC          28083
IIIB          20344
IIINOS         2404
Name: Breast - Adjusted AJCC 6th Stage (1988-2015), dtype: int64

Breast - Adjusted AJCC 6th T (1988-2015)
T1c            295402
T2             239024
Tis            226091
Blank(s)       166903
T1b            148491
TX Adjusted     59749
T1a             57804
Any T, Mets     45927
T3              42195
T1mic           17077
T4b             13088
T4d              9698
T4a              3209
T0               1136
T4c               671
Name: Breast - Adjusted AJCC 6th T (1988-2015), dtype: int64

Breast - Adjusted AJCC 6th N (1988-2015)
N0             806665
N1             193632
Blank(s)       166903
NX Adjusted     68641
N2              52213
N3              38411
Name: Breast - Adjusted AJCC 6th N (1988-2015), dtype: int64

Breast - Adjusted AJCC 6th M (1988-2015)
M0          1084601
Blank(s)     166903
M1            45927
MX            29034
Name: Breast - Adjusted AJCC 6th M (1988-2015), dtype: int64

## Drop unused columns

In [13]:
## cols to drop -- 6 columns
cols = ['Site recode ICD-O-3/WHO 2008',  'Lymph-vascular Invasion (2004+ varying by schema)',  'Tumor Size Summary (2016+)', 'Behavior recode for analysis', 'COD to site recode',
        'SEER cause-specific death classification',  'CS extension (2004-2015)']

In [14]:
data_1 = data3.drop(columns=cols)

In [15]:
data_1.columns

Index(['Sex', 'Summary stage 2000 (1998+)', 'Grade',
       'Race recode (W, B, AI, API)', 'Age recode with <1 year olds',
       'Primary Site - labeled', 'CS tumor size (2004-2015)',
       'Reason no cancer-directed surgery', 'Histologic Type ICD-O-3',
       'Behavior code ICD-O-3', 'Regional nodes positive (1988+)',
       'Regional nodes examined (1988+)',
       'Total number of in situ/malignant tumors for patient', 'Laterality',
       'ER Status Recode Breast Cancer (1990+)',
       'PR Status Recode Breast Cancer (1990+)',
       'SEER other cause of death classification', 'Survival months',
       'Survival months flag', 'Breast - Adjusted AJCC 6th Stage (1988-2015)',
       'Breast - Adjusted AJCC 6th T (1988-2015)',
       'Breast - Adjusted AJCC 6th N (1988-2015)',
       'Breast - Adjusted AJCC 6th M (1988-2015)'],
      dtype='object')

In [120]:
for name in data_1.columns:
    print('\n'+name)
    print(data_1[name].value_counts())

Sex
Female    1318896
Male         8980
Name: Sex, dtype: int64

Summary stage 2000 (1998+)
Localized           669337
Regional            318963
In situ             255703
Distant              58158
Unknown/unstaged     25715
Name: Summary stage 2000 (1998+), dtype: int64

Grade
Moderately differentiated; Grade II       506450
Poorly differentiated; Grade III          392618
Well differentiated; Grade I              244723
Unknown                                   156303
Undifferentiated; anaplastic; Grade IV     27782
Name: Grade, dtype: int64

Race recode (W, B, AI, API)
White                            1065269
Black                             141670
Asian or Pacific Islander         105440
Unknown                             8589
American Indian/Alaska Native       6908
Name: Race recode (W, B, AI, API), dtype: int64

Age recode with <1 year olds
60-64 years    168909
55-59 years    166301
65-69 years    161232
50-54 years    159674
45-49 years    137488
70-74 years    133537
75-79 years    108945
40-44 years     88800
80-84 years     77753
85+ years       64764
35-39 years     38347
30-34 years     15992
25-29 years      5085
20-24 years       935
15-19 years       100
10-14 years        11
05-09 years         2
01-04 years         1
Name: Age recode with <1 year olds, dtype: int64

Primary Site - labeled
C50.4-Upper-outer quadrant of breast    429181
C50.8-Overlapping lesion of breast      281484
C50.9-Breast, NOS                       225085
C50.2-Upper-inner quadrant of breast    138594
C50.5-Lower-outer quadrant of breast     90979
C50.1-Central portion of breast          74275
C50.3-Lower-inner quadrant of breast     72454
C50.0-Nipple                              8758
C50.6-Axillary tail of breast             7066
Name: Primary Site - labeled, dtype: int64

CS tumor size (2004-2015)
Blank(s)    431921
999          88667
015          51388
010          39758
012          35969
             ...
315              1
555              1
508              1
740              1
870              1
Name: CS tumor size (2004-2015), Length: 318, dtype: int64

Reason no cancer-directed surgery
Surgery performed                                                               1215193
Not recommended                                                                   72305
Recommended but not performed, unknown reason                                     11263
Recommended but not performed, patient refused                                     9233
Unknown; death certificate; or autopsy only (2003+)                                8018
Recommended, unknown if performed                                                  6961
Not recommended, contraindicated due to other cond; autopsy only (1973-2002)       4201
Not performed, patient died prior to recommended surgery                            702
Name: Reason no cancer-directed surgery, dtype: int64

Histologic Type ICD-O-3
8500    838273
8520    123197
8523     95921
8522     77815
8201     23652
         ...
8912         1
8350         1
8933         1
9581         1
8950         1
Name: Histologic Type ICD-O-3, Length: 176, dtype: int64

Behavior code ICD-O-3
Malignant    1072172
In situ       255704
Name: Behavior code ICD-O-3, dtype: int64

Regional nodes positive (1988+)
0     680184
98    327201
1     121394
2      48645
3      26215
       ...
70         1
63         1
59         1
88         1
87         1
Name: Regional nodes positive (1988+), Length: 80, dtype: int64

Regional nodes examined (1988+)
0     327201
1     182388
2     160203
3     112404
4      70271
       ...
80         1
73         1
83         1
71         1
82         1
Name: Regional nodes examined (1988+), Length: 88, dtype: int64

Total number of in situ/malignant tumors for patient
1          742240
2          255595
01         196416
3           55047
02          53194
4           10388
03          10245
5            1876
04           1864
6             454
05            336
7              75
06             51
8              39
07             18
Unknown        11
10              6
09              5
08              4
9               4
11              3
20              2
13              1
50              1
14              1
Name: Total number of in situ/malignant tumors for patient, dtype: int64

Laterality
Left - origin of primary                                 668924
Right - origin of primary                                646073
Paired site, but no information concerning laterality     11076
Only one side - side unspecified                           1182
Bilateral, single primary                                   621
Name: Laterality, dtype: int64

ER Status Recode Breast Cancer (1990+)
Positive      932914
Negative      209444
Unknown       184086
Borderline      1432
Name: ER Status Recode Breast Cancer (1990+), dtype: int64

PR Status Recode Breast Cancer (1990+)
Positive      788091
Negative      330857
Unknown       204551
Borderline      4377
Name: PR Status Recode Breast Cancer (1990+), dtype: int64

SEER other cause of death classification
Alive or dead due to cancer                                1148135
Dead (attributable to causes other than this cancer dx)     174132
Dead (missing/unknown COD)                                    5598
N/A not seq 0-59                                                11
Name: SEER other cause of death classification, dtype: int64

Survival months
0000    15707
0001    12616
0002    12326
0004    12037
0006    11362
        ...
212       246
211       242
213       234
209       206
215       205
Name: Survival months, Length: 433, dtype: int64

Survival months flag
Complete dates are available and there are more than 0 days of survival      1109681
Incomplete dates are available and there cannot be zero days of follow-up     208819
Not calculated because a Death Certificate Only or Autopsy Only case            4929
Incomplete dates are available and there could be zero days of follow-up        2519
Complete dates are available and there are 0 days of survival                   1928
Name: Survival months flag, dtype: int64

## Removing instances based on features

**NOTE: not going to IMPUTE. Will remove instances that do not have specific features. Otherwise, will give them another category as "Unknown"**

data_4 and data_3 when combined have different outputs initially 1317508 and 1318896 due to the NAs in the additional 4 variables to data_4 that cause it to also drop specific rows

In [19]:
remove = [('Sex', ['Male']), 
          ('Summary stage 2000 (1998+)', ['Unknown/unstaged']), 
          ('Grade', ['Unknown']), 
          ('CS tumor size (2004-2015)', ['Blank(s)', '999', '888', '996', '997', '998', '995', '994', '993', '992', '991', '990', '000']), 
          ('Reason no cancer-directed surgery', ['Unknown; death certificate; or autopsy only (2003+)']),
          ('Regional nodes positive (1988+)', [98, 97, 95]), 
          ('Regional nodes examined (1988+)', [0, 95, 96, 97, 98, 99]),  
          ('Total number of in situ/malignant tumors for patient', ['Unknown']), 
          ('Survival months', ['Unknown']),
          #For some reason I did this separately? 
          ('Survival months flag',['Incomplete dates are available and there cannot be zero days of follow-up',
       'Incomplete dates are available and there could be zero days of follow-up']),
          ('SEER other cause of death classification', ['Dead (attributable to causes other than this cancer dx)', 'Dead (missing/unknown COD)']),
          #Staging Variables -- con catentating them 
          ('Breast - Adjusted AJCC 6th Stage (1988-2015)', ['NA', 'UNK Stage', 'Blank(s)']),
          ('Breast - Adjusted AJCC 6th T (1988-2015)', ['TX', 'T0', 'TX Adjusted', 'Any T, Mets', 'NA', 'Blank(s)']),
          ('Breast - Adjusted AJCC 6th N (1988-2015)', ['NX Adjusted', 'Blank(s)''NA']),
          ('Breast - Adjusted AJCC 6th M (1988-2015)', ['MX', 'NA'])
         ]
#9 features 
count = 0
for variable, value in remove:
    col = data_1[[variable]].replace(value, np.nan)
    data_1[[variable]] = col[[variable]]
    data_2 = data_1.dropna()
    
    count = count + 1
    print(variable+" ")
    print('{}\n'.format(count))
    print(data_2.shape)

#df_scale = df_drop_1[['CS tumor size (2004-2015)']].replace(['Blank(s)'], np.nan)
#df_drop_1[['CS tumor size (2004-2015)']] = df_scale[['CS tumor size (2004-2015)']]
#df_drop_1 = df_drop.dropna()

Sex
1

(447979, 23)
Summary stage 2000 (1998+)
2

(447979, 23)
Grade
3

(447979, 23)
CS tumor size (2004-2015)
4

(447979, 23)
Reason no cancer-directed surgery
5

(447979, 23)
Regional nodes positive (1988+)
6

(447979, 23)
Regional nodes examined (1988+)
7

(447979, 23)
Total number of in situ/malignant tumors for patient
8

(447979, 23)
Survival months
9

(447979, 23)
Survival months flag
10

(447979, 23)
SEER other cause of death classification
11

(447979, 23)
Breast - Adjusted AJCC 6th Stage (1988-2015)
12

(445708, 23)
Breast - Adjusted AJCC 6th T (1988-2015)
13

(439727, 23)
Breast - Adjusted AJCC 6th N (1988-2015)
14

(439719, 23)
Breast - Adjusted AJCC 6th M (1988-2015)
15

(439719, 23)

# Testing

In [19]:
remove = [('Sex', ['Male']), 
          ('Summary stage 2000 (1998+)', ['Unknown/unstaged']), 
          ('Grade', ['Unknown']), 
          ('CS tumor size (2004-2015)', ['Blank(s)', '999', '888', '996', '997', '998', '995', '994', '993', '992', '991', '990', '000']), 
          ('Reason no cancer-directed surgery', ['Unknown; death certificate; or autopsy only (2003+)']),
          ('Regional nodes positive (1988+)', [98, 97, 95]), 
          ('Regional nodes examined (1988+)', [0, 95, 96, 97, 98, 99]),  
          ('Total number of in situ/malignant tumors for patient', ['Unknown']), 
          ('Survival months', ['Unknown']),
          #For some reason I did this separately? 
          ('Survival months flag',['Incomplete dates are available and there cannot be zero days of follow-up',
       'Incomplete dates are available and there could be zero days of follow-up']),
          ('SEER other cause of death classification', ['Dead (attributable to causes other than this cancer dx)', 'Dead (missing/unknown COD)'])
          #Staging Variables -- con catentating them 
          
         ]
#9 features 
count = 0
for variable, value in remove:
    col = data3[[variable]].replace(value, np.nan)
    data3[[variable]] = col[[variable]]
    data0 = data3.dropna()
    
    count = count + 1
    print(variable+" ")
    print('{}\n'.format(count))
    print(data0.shape)

Sex
1

(1318896, 26)
Summary stage 2000 (1998+)
2

(1293441, 26)
Grade
3

(1155570, 26)
CS tumor size (2004-2015)
4

(727211, 26)
Reason no cancer-directed surgery
5

(726825, 26)
Regional nodes positive (1988+)
6

(589208, 26)
Regional nodes examined (1988+)
7

(584130, 26)
Total number of in situ/malignant tumors for patient
8

(584127, 26)
Survival months
9

(584127, 26)
Survival months flag
10

(497097, 26)
SEER other cause of death classification
11

(448215, 26)

# End Testing

In [20]:
data_2.columns

Index(['Sex', 'Summary stage 2000 (1998+)', 'Grade',
       'Race recode (W, B, AI, API)', 'Age recode with <1 year olds',
       'Primary Site - labeled', 'CS tumor size (2004-2015)',
       'Reason no cancer-directed surgery', 'Histologic Type ICD-O-3',
       'Behavior code ICD-O-3', 'Regional nodes positive (1988+)',
       'Regional nodes examined (1988+)',
       'Total number of in situ/malignant tumors for patient', 'Laterality',
       'ER Status Recode Breast Cancer (1990+)',
       'PR Status Recode Breast Cancer (1990+)',
       'SEER other cause of death classification', 'Survival months',
       'Survival months flag', 'Breast - Adjusted AJCC 6th Stage (1988-2015)',
       'Breast - Adjusted AJCC 6th T (1988-2015)',
       'Breast - Adjusted AJCC 6th N (1988-2015)',
       'Breast - Adjusted AJCC 6th M (1988-2015)'],
      dtype='object')

In [21]:
data_2.shape

(439719, 23)

data-2.txt shape is 448215 rows
data-3.txt shape is 439719 rows

In [22]:
for name in data_2.columns:
    print('\n'+name)
    print(data_2[name].value_counts())

Sex
Female    439719
Name: Sex, dtype: int64

Summary stage 2000 (1998+)
Localized    274633
Regional     132744
In situ       31132
Distant        1210
Name: Summary stage 2000 (1998+), dtype: int64

Grade
Moderately differentiated; Grade II       190719
Poorly differentiated; Grade III          146821
Well differentiated; Grade I               95908
Undifferentiated; anaplastic; Grade IV      6271
Name: Grade, dtype: int64

Race recode (W, B, AI, API)
White                            349122
Black                             43230
Asian or Pacific Islander         43027
American Indian/Alaska Native      2266
Unknown                            2074
Name: Race recode (W, B, AI, API), dtype: int64

Age recode with <1 year olds
60-64 years    62172
55-59 years    60786
50-54 years    59068
65-69 years    55998
45-49 years    52318
70-74 years    41182
40-44 years    33807
75-79 years    28490
80-84 years    15437
35-39 years    15009
85+ years       6869
30-34 years     6274
25-29 years     1971
20-24 years      318
15-19 years       18
05-09 years        1
10-14 years        1
Name: Age recode with <1 year olds, dtype: int64

Primary Site - labeled
C50.4-Upper-outer quadrant of breast    151804
C50.8-Overlapping lesion of breast       99928
C50.2-Upper-inner quadrant of breast     53265
C50.9-Breast, NOS                        50675
C50.5-Lower-outer quadrant of breast     33582
C50.3-Lower-inner quadrant of breast     25363
C50.1-Central portion of breast          21057
C50.6-Axillary tail of breast             2437
C50.0-Nipple                              1608
Name: Primary Site - labeled, dtype: int64

CS tumor size (2004-2015)
015    31029
010    22245
012    21761
020    19998
025    19662
       ...
213        1
405        1
680        1
212        1
555        1
Name: CS tumor size (2004-2015), Length: 241, dtype: int64

Reason no cancer-directed surgery
Surgery performed                                                               438092
Not recommended                                                                   1095
Recommended, unknown if performed                                                  325
Recommended but not performed, unknown reason                                       91
Recommended but not performed, patient refused                                      84
Not recommended, contraindicated due to other cond; autopsy only (1973-2002)        26
Not performed, patient died prior to recommended surgery                             6
Name: Reason no cancer-directed surgery, dtype: int64

Histologic Type ICD-O-3
8500    314681
8520     34051
8522     29947
8523     25336
8480      7272
         ...
8147         1
8407         1
8413         1
8154         1
8542         1
Name: Histologic Type ICD-O-3, Length: 90, dtype: int64

Behavior code ICD-O-3
Malignant    408587
In situ       31132
Name: Behavior code ICD-O-3, dtype: int64

Regional nodes positive (1988+)
0.0     313820
1.0      55455
2.0      22330
3.0      11736
4.0       7694
         ...
70.0         1
90.0         1
71.0         1
84.0         1
63.0         1
Name: Regional nodes positive (1988+), Length: 66, dtype: int64

Regional nodes examined (1988+)
1.0     91377
2.0     82124
3.0     57064
4.0     35147
5.0     22772
        ...
88.0        1
83.0        1
75.0        1
81.0        1
77.0        1
Name: Regional nodes examined (1988+), Length: 79, dtype: int64

Total number of in situ/malignant tumors for patient
1     247524
01     82590
2      72743
02     17444
3      13664
03      2476
4       2315
5        423
04       346
6         79
05        63
8         15
7         14
06         9
07         7
9          2
09         1
10         1
13         1
08         1
11         1
Name: Total number of in situ/malignant tumors for patient, dtype: int64

Laterality
Left - origin of primary                                 222708
Right - origin of primary                                216960
Only one side - side unspecified                             29
Bilateral, single primary                                    15
Paired site, but no information concerning laterality         7
Name: Laterality, dtype: int64

ER Status Recode Breast Cancer (1990+)
Positive      350638
Negative       77254
Unknown        11362
Borderline       465
Name: ER Status Recode Breast Cancer (1990+), dtype: int64

PR Status Recode Breast Cancer (1990+)
Positive      301015
Negative      121432
Unknown        15831
Borderline      1441
Name: PR Status Recode Breast Cancer (1990+), dtype: int64

SEER other cause of death classification
Alive or dead due to cancer    439719
Name: SEER other cause of death classification, dtype: int64

Survival months
0030    4322
0027    4311
0038    4242
0026    4227
0025    4208
        ...
14         8
13         7
16         7
20         7
12         6
Name: Survival months, Length: 336, dtype: int64

Survival months flag
Complete dates are available and there are more than 0 days of survival    439697
Complete dates are available and there are 0 days of survival                  22
Name: Survival months flag, dtype: int64

Breast - Adjusted AJCC 6th Stage (1988-2015)
I       208925
IIA     104429
IIB      46976
0        31296
IIIA     29460
IIIC     12800
IIIB      5833
Name: Breast - Adjusted AJCC 6th Stage (1988-2015), dtype: int64

Breast - Adjusted AJCC 6th T (1988-2015)
T1c      150431
T2       121283
T1b       75426
Tis       31296
T1a       29794
T3        21266
T4b        4184
T1mic      2710
T4d        2306
T4a         894
T4c         129
Name: Breast - Adjusted AJCC 6th T (1988-2015), dtype: int64

Breast - Adjusted AJCC 6th N (1988-2015)
N0    310515
N1     92986
N2     23418
N3     12800
Name: Breast - Adjusted AJCC 6th N (1988-2015), dtype: int64

Breast - Adjusted AJCC 6th M (1988-2015)
M0    439719
Name: Breast - Adjusted AJCC 6th M (1988-2015), dtype: int64

## Dropping the cause of death variable and survival months

In [23]:
data_3 = data_2.drop(columns=['SEER other cause of death classification', 'Survival months flag'])

In [24]:
data_3.columns

Index(['Sex', 'Summary stage 2000 (1998+)', 'Grade',
       'Race recode (W, B, AI, API)', 'Age recode with <1 year olds',
       'Primary Site - labeled', 'CS tumor size (2004-2015)',
       'Reason no cancer-directed surgery', 'Histologic Type ICD-O-3',
       'Behavior code ICD-O-3', 'Regional nodes positive (1988+)',
       'Regional nodes examined (1988+)',
       'Total number of in situ/malignant tumors for patient', 'Laterality',
       'ER Status Recode Breast Cancer (1990+)',
       'PR Status Recode Breast Cancer (1990+)', 'Survival months',
       'Breast - Adjusted AJCC 6th Stage (1988-2015)',
       'Breast - Adjusted AJCC 6th T (1988-2015)',
       'Breast - Adjusted AJCC 6th N (1988-2015)',
       'Breast - Adjusted AJCC 6th M (1988-2015)'],
      dtype='object')

## Changing Histologic Type ICD-O-3 variable

In [25]:
import math

In [26]:
data_3['histo'] = data_3['Histologic Type ICD-O-3'].apply(lambda x: math.floor(x/10))

## Replacing TMN Staging Variables with Numbers

In [27]:
data_3['Breast - Adjusted AJCC 6th T (1988-2015)'] = data_3['Breast - Adjusted AJCC 6th T (1988-2015)'].replace(['T0', 'Tis', 'T1mic', 'T1a', 'T1b', 'T1c', 'T2', 'T3', 'T4a', 'T4b', 'T4c', 'T4d'], 
                                                           [0, 0, 0.1, 0.25, 0.75, 1.5, 3.0, 5.0, 6.0, 7.0, 8.0, 9.0])

In [28]:
data_3['Breast - Adjusted AJCC 6th N (1988-2015)'] = data_3['Breast - Adjusted AJCC 6th N (1988-2015)'].replace(['N0', 'N1', 'N2', 'N3'],[0, 2, 6.5, 10])

In [29]:
data_3['Breast - Adjusted AJCC 6th M (1988-2015)'] = data_3['Breast - Adjusted AJCC 6th M (1988-2015)'].replace('M0', 0)

## Processing to Binary Label

Survivability will depend on whether the patient lived longer than 5 years (aka 60 months) after first diagnosis as based off previous papers doing this same task).

In [30]:
target = data_3[['Survival months']]

In [31]:
target

        Survival months
5                  0123
10                 0085
33                 0061
47                 0162
50                 0143
...                 ...
1327866            0156
1327867            0149
1327869            0126
1327872            0149
1327874            0154

[439719 rows x 1 columns]

In [32]:
target_1 = pd.to_numeric(target['Survival months']).to_frame()

In [33]:
target_1

         Survival months
5                    123
10                    85
33                    61
47                   162
50                   143
...                  ...
1327866              156
1327867              149
1327869              126
1327872              149
1327874              154

[439719 rows x 1 columns]

In [34]:
target_1[target_1['Survival months'] < 60] = -1 #did not survive

In [35]:
target_1[target_1['Survival months'] > 60] = 1 #survived

In [36]:
target_1[target_1['Survival months'] == 60] = 1 #survived

In [37]:
target_1

         Survival months
5                      1
10                     1
33                     1
47                     1
50                     1
...                  ...
1327866                1
1327867                1
1327869                1
1327872                1
1327874                1

[439719 rows x 1 columns]

In [38]:
target_1['Survival months'].value_counts()

 1    278714
-1    161005
Name: Survival months, dtype: int64

In [39]:
281919+166296

448215

1 = survived (lived 5 years or longer) --> 281919 instances

0 = did not survive (lived less than 5 years) --> 166296 instances

In [40]:
data_4 = data_3.drop(columns=['Survival months', 'Sex'])

In [41]:
data_4

,Summary stage 2000 (1998+),Grade,"Race recode (W, B, AI, API)",Age recode with <1 year olds,Primary Site - labeled,CS tumor size (2004-2015),Reason no cancer-directed surgery,Histologic Type ICD-O-3,Behavior code ICD-O-3,Regional nodes positive (1988+),Regional nodes examined (1988+),Total number of in situ/malignant tumors for patient,Laterality,ER Status Recode Breast Cancer (1990+),PR Status Recode Breast Cancer (1990+),Breast - Adjusted AJCC 6th Stage (1988-2015),Breast - Adjusted AJCC 6th T (1988-2015),Breast - Adjusted AJCC 6th N (1988-2015),Breast - Adjusted AJCC 6th M (1988-2015)
5,In situ,Undifferentiated; anaplastic; Grade IV,White,85+ years,"C50.9-Breast, NOS",018,Surgery performed,850,In situ,0.0,1.0,3,Right - origin of primary,Negative,Negative,0,0.0,0.0,0
10,In situ,Undifferentiated; anaplastic; Grade IV,White,60-64 years,C50.1-Central portion of breast,025,Surgery performed,852,In situ,0.0,1.0,2,Left - origin of primary,Negative,Negative,0,0.0,0.0,0
33,In situ,Poorly differentiated; Grade III,Asian or Pacific Islander,55-59 years,C50.4-Upper-outer quadrant of breast,030,Surgery performed,852,In situ,0.0,1.0,3,Right - origin of primary,Negative,Negative,0,0.0,0.0,0
47,In situ,Undifferentiated; anaplastic; Grade IV,White,75-79 years,C50.4-Upper-outer quadrant of breast,005,Surgery performed,850,In situ,0.0,2.0,3,Left - origin of primary,Negative,Negative,0,0.0,0.0,0
50,In situ,Moderately differentiated; Grade II,Asian or Pacific Islander,60-64 years,C50.2-Upper-inner quadrant of breast,033,Surgery performed,852,In situ,0.0,2.0,2,Left - origin of primary,Positive,Positive,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327866,Regional,Moderately differentiated; Grade II,White,50-54 years,C50.4-Upper-outer quadrant of breast,012,Surgery performed,852,Malignant,10.0,24.0,1,Left - origin of primary,Positive,Positive,IIA,1.5,2.0,0
1327867,Localized,Moderately differentiated; Grade II,White,65-69 years,C50.8-Overlapping lesion of breast,012,Surgery performed,850,Malignant,0.0,2.0,1,Left - origin of primary,Positive,Positive,I,1.5,0.0,0
1327869,Localized,Moderately differentiated; Grade II,White,30-34 years,C50.2-Upper-inner quadrant of breast,015,Surgery performed,850,Malignant,0.0,4.0,1,Right - origin of primary,Positive,Positive,I,1.5,0.0,0
1327872,Localized,Well differentiated; Grade I,White,55-59 years,C50.2-Upper-inner quadrant of breast,020,Surgery performed,852,Malignant,0.0,2.0,1,Left - origin of primary,Positive,Negative,I,1.5,0.0,0
1327874,Regional,Poorly differentiated; Grade III,White,55-59 years,C50.8-Overlapping lesion of breast,035,Surgery performed,850,Malignant,12.0,13.0,1,Left - origin of primary,Positive,Positive,IIIC,3.0,10.0,0

In [42]:
data_4.columns

Index(['Summary stage 2000 (1998+)', 'Grade', 'Race recode (W, B, AI, API)',
       'Age recode with <1 year olds', 'Primary Site - labeled',
       'CS tumor size (2004-2015)', 'Reason no cancer-directed surgery',
       'Histologic Type ICD-O-3', 'Behavior code ICD-O-3',
       'Regional nodes positive (1988+)', 'Regional nodes examined (1988+)',
       'Total number of in situ/malignant tumors for patient', 'Laterality',
       'ER Status Recode Breast Cancer (1990+)',
       'PR Status Recode Breast Cancer (1990+)',
       'Breast - Adjusted AJCC 6th Stage (1988-2015)',
       'Breast - Adjusted AJCC 6th T (1988-2015)',
       'Breast - Adjusted AJCC 6th N (1988-2015)',
       'Breast - Adjusted AJCC 6th M (1988-2015)'],
      dtype='object')

# Splitting into Train/Test 
Because you can't have data leak -- where information about the testing set is leaked into the training set? they have to be scaled independently

## Changing y-variable

In [43]:
target = pd.DataFrame(target_1.to_numpy(), columns=['Survival months'])
target

        Survival months
0                     1
1                     1
2                     1
3                     1
4                     1
...                 ...
439714                1
439715                1
439716                1
439717                1
439718                1

[439719 rows x 1 columns]

In [49]:
data_5 = pd.DataFrame(data_4.to_numpy(), columns=['Summary stage 2000 (1998+)', 'Grade', 'Race recode (W, B, AI, API)',
       'Age recode with <1 year olds', 'Primary Site - labeled',
       'CS tumor size (2004-2015)', 'Reason no cancer-directed surgery',
       'Histologic Type ICD-O-3', 'Behavior code ICD-O-3',
       'Regional nodes positive (1988+)', 'Regional nodes examined (1988+)',
       'Total number of in situ/malignant tumors for patient', 'Laterality',
       'ER Status Recode Breast Cancer (1990+)',
       'PR Status Recode Breast Cancer (1990+)',
       'Breast - Adjusted AJCC 6th Stage (1988-2015)',
       'Breast - Adjusted AJCC 6th T (1988-2015)',
       'Breast - Adjusted AJCC 6th N (1988-2015)',
       'Breast - Adjusted AJCC 6th M (1988-2015)'])
data_6 = pd.concat([data_5, target], axis=1)
data_6

,Summary stage 2000 (1998+),Grade,"Race recode (W, B, AI, API)",Age recode with <1 year olds,Primary Site - labeled,CS tumor size (2004-2015),Reason no cancer-directed surgery,Histologic Type ICD-O-3,Behavior code ICD-O-3,Regional nodes positive (1988+),Regional nodes examined (1988+),Total number of in situ/malignant tumors for patient,Laterality,ER Status Recode Breast Cancer (1990+),PR Status Recode Breast Cancer (1990+),Breast - Adjusted AJCC 6th Stage (1988-2015),Breast - Adjusted AJCC 6th T (1988-2015),Breast - Adjusted AJCC 6th N (1988-2015),Breast - Adjusted AJCC 6th M (1988-2015),Survival months
0,In situ,Undifferentiated; anaplastic; Grade IV,White,85+ years,"C50.9-Breast, NOS",018,Surgery performed,850,In situ,0,1,3,Right - origin of primary,Negative,Negative,0,0,0,0,1
1,In situ,Undifferentiated; anaplastic; Grade IV,White,60-64 years,C50.1-Central portion of breast,025,Surgery performed,852,In situ,0,1,2,Left - origin of primary,Negative,Negative,0,0,0,0,1
2,In situ,Poorly differentiated; Grade III,Asian or Pacific Islander,55-59 years,C50.4-Upper-outer quadrant of breast,030,Surgery performed,852,In situ,0,1,3,Right - origin of primary,Negative,Negative,0,0,0,0,1
3,In situ,Undifferentiated; anaplastic; Grade IV,White,75-79 years,C50.4-Upper-outer quadrant of breast,005,Surgery performed,850,In situ,0,2,3,Left - origin of primary,Negative,Negative,0,0,0,0,1
4,In situ,Moderately differentiated; Grade II,Asian or Pacific Islander,60-64 years,C50.2-Upper-inner quadrant of breast,033,Surgery performed,852,In situ,0,2,2,Left - origin of primary,Positive,Positive,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439714,Regional,Moderately differentiated; Grade II,White,50-54 years,C50.4-Upper-outer quadrant of breast,012,Surgery performed,852,Malignant,10,24,1,Left - origin of primary,Positive,Positive,IIA,1.5,2,0,1
439715,Localized,Moderately differentiated; Grade II,White,65-69 years,C50.8-Overlapping lesion of breast,012,Surgery performed,850,Malignant,0,2,1,Left - origin of primary,Positive,Positive,I,1.5,0,0,1
439716,Localized,Moderately differentiated; Grade II,White,30-34 years,C50.2-Upper-inner quadrant of breast,015,Surgery performed,850,Malignant,0,4,1,Right - origin of primary,Positive,Positive,I,1.5,0,0,1
439717,Localized,Well differentiated; Grade I,White,55-59 years,C50.2-Upper-inner quadrant of breast,020,Surgery performed,852,Malignant,0,2,1,Left - origin of primary,Positive,Negative,I,1.5,0,0,1
439718,Regional,Poorly differentiated; Grade III,White,55-59 years,C50.8-Overlapping lesion of breast,035,Surgery performed,850,Malignant,12,13,1,Left - origin of primary,Positive,Positive,IIIC,3,10,0,1

## Resampling
having the same number of survived and did not survive

In [50]:
data_6['Survival months'].value_counts()

 1    278714
-1    161005
Name: Survival months, dtype: int64

In [51]:
low = data_6[['Survival months']].value_counts().min()
low

161005

Choosing the number of random samples that have (data-2 166296)  (data-3 161005) (data-1 171866) for the survived (1) cases

In [52]:
samples = data_6[data_6['Survival months'] == 1].index.values
index_range = range(samples.shape[0])
indexes = np.random.choice(index_range, size=low, replace=False)
subsample =  samples[indexes].tolist()
d_1 = data_6.loc[subsample, :]

In [53]:
d_1

,Summary stage 2000 (1998+),Grade,"Race recode (W, B, AI, API)",Age recode with <1 year olds,Primary Site - labeled,CS tumor size (2004-2015),Reason no cancer-directed surgery,Histologic Type ICD-O-3,Behavior code ICD-O-3,Regional nodes positive (1988+),Regional nodes examined (1988+),Total number of in situ/malignant tumors for patient,Laterality,ER Status Recode Breast Cancer (1990+),PR Status Recode Breast Cancer (1990+),Breast - Adjusted AJCC 6th Stage (1988-2015),Breast - Adjusted AJCC 6th T (1988-2015),Breast - Adjusted AJCC 6th N (1988-2015),Breast - Adjusted AJCC 6th M (1988-2015),Survival months
99395,Localized,Poorly differentiated; Grade III,Asian or Pacific Islander,60-64 years,C50.4-Upper-outer quadrant of breast,028,Surgery performed,850,Malignant,0,12,1,Right - origin of primary,Negative,Negative,IIA,3,0,0,1
438302,Localized,Moderately differentiated; Grade II,White,50-54 years,C50.4-Upper-outer quadrant of breast,008,Surgery performed,850,Malignant,0,3,1,Left - origin of primary,Positive,Positive,I,0.75,0,0,1
14227,In situ,Moderately differentiated; Grade II,Asian or Pacific Islander,50-54 years,C50.5-Lower-outer quadrant of breast,025,Surgery performed,852,In situ,0,6,1,Right - origin of primary,Positive,Positive,0,0,0,0,1
201514,Localized,Well differentiated; Grade I,White,60-64 years,C50.4-Upper-outer quadrant of breast,024,Surgery performed,852,Malignant,0,5,2,Right - origin of primary,Positive,Positive,IIA,3,0,0,1
403716,Localized,Well differentiated; Grade I,White,55-59 years,C50.3-Lower-inner quadrant of breast,016,Surgery performed,850,Malignant,0,2,1,Left - origin of primary,Positive,Positive,I,1.5,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343737,Localized,Moderately differentiated; Grade II,Black,60-64 years,C50.4-Upper-outer quadrant of breast,013,Surgery performed,850,Malignant,0,8,1,Right - origin of primary,Negative,Negative,I,1.5,0,0,1
334564,Localized,Moderately differentiated; Grade II,White,60-64 years,C50.3-Lower-inner quadrant of breast,021,Surgery performed,852,Malignant,0,1,1,Right - origin of primary,Positive,Positive,IIA,3,0,0,1
259010,Localized,Well differentiated; Grade I,White,80-84 years,"C50.9-Breast, NOS",009,Surgery performed,850,Malignant,0,7,02,Left - origin of primary,Positive,Positive,I,0.75,0,0,1
263628,Localized,Well differentiated; Grade I,White,50-54 years,C50.4-Upper-outer quadrant of breast,007,Surgery performed,852,Malignant,0,4,01,Left - origin of primary,Positive,Positive,I,0.75,0,0,1
184039,Regional,Poorly differentiated; Grade III,White,65-69 years,C50.8-Overlapping lesion of breast,017,Surgery performed,850,Malignant,3,10,1,Right - origin of primary,Positive,Positive,IIA,1.5,2,0,1

In [54]:
samples_0 = data_6[data_6['Survival months'] == -1].index.values
d_0 = data_6.loc[samples_0, :]

In [55]:
d_0

,Summary stage 2000 (1998+),Grade,"Race recode (W, B, AI, API)",Age recode with <1 year olds,Primary Site - labeled,CS tumor size (2004-2015),Reason no cancer-directed surgery,Histologic Type ICD-O-3,Behavior code ICD-O-3,Regional nodes positive (1988+),Regional nodes examined (1988+),Total number of in situ/malignant tumors for patient,Laterality,ER Status Recode Breast Cancer (1990+),PR Status Recode Breast Cancer (1990+),Breast - Adjusted AJCC 6th Stage (1988-2015),Breast - Adjusted AJCC 6th T (1988-2015),Breast - Adjusted AJCC 6th N (1988-2015),Breast - Adjusted AJCC 6th M (1988-2015),Survival months
6,In situ,Moderately differentiated; Grade II,Asian or Pacific Islander,60-64 years,C50.4-Upper-outer quadrant of breast,008,Surgery performed,852,In situ,0,1,2,Left - origin of primary,Positive,Positive,0,0,0,0,-1
17,In situ,Poorly differentiated; Grade III,Black,50-54 years,C50.4-Upper-outer quadrant of breast,025,Surgery performed,852,In situ,0,2,3,Right - origin of primary,Positive,Positive,0,0,0,0,-1
18,In situ,Poorly differentiated; Grade III,Asian or Pacific Islander,55-59 years,C50.8-Overlapping lesion of breast,020,Surgery performed,850,In situ,0,1,2,Left - origin of primary,Positive,Positive,0,0,0,0,-1
24,In situ,Moderately differentiated; Grade II,Black,55-59 years,"C50.9-Breast, NOS",050,Surgery performed,852,In situ,0,2,2,Right - origin of primary,Positive,Positive,0,0,0,0,-1
33,In situ,Moderately differentiated; Grade II,White,40-44 years,C50.2-Upper-inner quadrant of breast,018,Surgery performed,850,In situ,0,2,2,Right - origin of primary,Positive,Positive,0,0,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439675,Localized,Well differentiated; Grade I,White,65-69 years,C50.4-Upper-outer quadrant of breast,008,Surgery performed,850,Malignant,0,5,2,Left - origin of primary,Positive,Positive,I,0.75,0,0,-1
439679,Localized,Poorly differentiated; Grade III,White,80-84 years,C50.4-Upper-outer quadrant of breast,017,Surgery performed,850,Malignant,0,6,1,Left - origin of primary,Positive,Positive,I,1.5,0,0,-1
439684,Regional,Moderately differentiated; Grade II,Asian or Pacific Islander,50-54 years,C50.1-Central portion of breast,040,Surgery performed,850,Malignant,5,6,1,Right - origin of primary,Positive,Positive,IIIA,3,6.5,0,-1
439695,Localized,Moderately differentiated; Grade II,Asian or Pacific Islander,70-74 years,C50.8-Overlapping lesion of breast,008,Surgery performed,850,Malignant,0,2,1,Left - origin of primary,Positive,Positive,I,0.75,0,0,-1
439705,Localized,Moderately differentiated; Grade II,White,45-49 years,"C50.9-Breast, NOS",015,Surgery performed,850,Malignant,0,5,1,Left - origin of primary,Positive,Positive,I,1.5,0,0,-1

In [56]:
d_final = pd.concat([d_1, d_0])

In [57]:
d_final[['Survival months']].value_counts()

Survival months
 1                 161005
-1                 161005
dtype: int64

In [58]:
d_final

,Summary stage 2000 (1998+),Grade,"Race recode (W, B, AI, API)",Age recode with <1 year olds,Primary Site - labeled,CS tumor size (2004-2015),Reason no cancer-directed surgery,Histologic Type ICD-O-3,Behavior code ICD-O-3,Regional nodes positive (1988+),Regional nodes examined (1988+),Total number of in situ/malignant tumors for patient,Laterality,ER Status Recode Breast Cancer (1990+),PR Status Recode Breast Cancer (1990+),Breast - Adjusted AJCC 6th Stage (1988-2015),Breast - Adjusted AJCC 6th T (1988-2015),Breast - Adjusted AJCC 6th N (1988-2015),Breast - Adjusted AJCC 6th M (1988-2015),Survival months
99395,Localized,Poorly differentiated; Grade III,Asian or Pacific Islander,60-64 years,C50.4-Upper-outer quadrant of breast,028,Surgery performed,850,Malignant,0,12,1,Right - origin of primary,Negative,Negative,IIA,3,0,0,1
438302,Localized,Moderately differentiated; Grade II,White,50-54 years,C50.4-Upper-outer quadrant of breast,008,Surgery performed,850,Malignant,0,3,1,Left - origin of primary,Positive,Positive,I,0.75,0,0,1
14227,In situ,Moderately differentiated; Grade II,Asian or Pacific Islander,50-54 years,C50.5-Lower-outer quadrant of breast,025,Surgery performed,852,In situ,0,6,1,Right - origin of primary,Positive,Positive,0,0,0,0,1
201514,Localized,Well differentiated; Grade I,White,60-64 years,C50.4-Upper-outer quadrant of breast,024,Surgery performed,852,Malignant,0,5,2,Right - origin of primary,Positive,Positive,IIA,3,0,0,1
403716,Localized,Well differentiated; Grade I,White,55-59 years,C50.3-Lower-inner quadrant of breast,016,Surgery performed,850,Malignant,0,2,1,Left - origin of primary,Positive,Positive,I,1.5,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439675,Localized,Well differentiated; Grade I,White,65-69 years,C50.4-Upper-outer quadrant of breast,008,Surgery performed,850,Malignant,0,5,2,Left - origin of primary,Positive,Positive,I,0.75,0,0,-1
439679,Localized,Poorly differentiated; Grade III,White,80-84 years,C50.4-Upper-outer quadrant of breast,017,Surgery performed,850,Malignant,0,6,1,Left - origin of primary,Positive,Positive,I,1.5,0,0,-1
439684,Regional,Moderately differentiated; Grade II,Asian or Pacific Islander,50-54 years,C50.1-Central portion of breast,040,Surgery performed,850,Malignant,5,6,1,Right - origin of primary,Positive,Positive,IIIA,3,6.5,0,-1
439695,Localized,Moderately differentiated; Grade II,Asian or Pacific Islander,70-74 years,C50.8-Overlapping lesion of breast,008,Surgery performed,850,Malignant,0,2,1,Left - origin of primary,Positive,Positive,I,0.75,0,0,-1
439705,Localized,Moderately differentiated; Grade II,White,45-49 years,"C50.9-Breast, NOS",015,Surgery performed,850,Malignant,0,5,1,Left - origin of primary,Positive,Positive,I,1.5,0,0,-1

In [59]:
d_shuffle = d_final.sample(frac=1)

In [60]:
d_shuffle

,Summary stage 2000 (1998+),Grade,"Race recode (W, B, AI, API)",Age recode with <1 year olds,Primary Site - labeled,CS tumor size (2004-2015),Reason no cancer-directed surgery,Histologic Type ICD-O-3,Behavior code ICD-O-3,Regional nodes positive (1988+),Regional nodes examined (1988+),Total number of in situ/malignant tumors for patient,Laterality,ER Status Recode Breast Cancer (1990+),PR Status Recode Breast Cancer (1990+),Breast - Adjusted AJCC 6th Stage (1988-2015),Breast - Adjusted AJCC 6th T (1988-2015),Breast - Adjusted AJCC 6th N (1988-2015),Breast - Adjusted AJCC 6th M (1988-2015),Survival months
376349,Regional,Well differentiated; Grade I,White,75-79 years,C50.5-Lower-outer quadrant of breast,016,Surgery performed,850,Malignant,1,1,1,Right - origin of primary,Positive,Positive,IIA,1.5,2,0,-1
80511,Regional,Poorly differentiated; Grade III,White,75-79 years,C50.8-Overlapping lesion of breast,055,Surgery performed,850,Malignant,1,11,1,Right - origin of primary,Positive,Negative,IIIA,5,2,0,-1
17513,In situ,Poorly differentiated; Grade III,White,45-49 years,C50.2-Upper-inner quadrant of breast,032,Surgery performed,850,In situ,0,1,1,Left - origin of primary,Negative,Negative,0,0,0,0,-1
272156,Regional,Poorly differentiated; Grade III,Black,50-54 years,C50.4-Upper-outer quadrant of breast,024,Surgery performed,850,Malignant,31,35,01,Right - origin of primary,Positive,Positive,IIIC,3,10,0,-1
193740,Regional,Poorly differentiated; Grade III,White,40-44 years,"C50.9-Breast, NOS",026,Surgery performed,850,Malignant,1,20,1,Left - origin of primary,Positive,Negative,IIIB,7,6.5,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405886,Distant,Moderately differentiated; Grade II,White,40-44 years,C50.1-Central portion of breast,084,Surgery performed,852,Malignant,18,25,1,Right - origin of primary,Positive,Positive,IIIC,5,10,0,1
33605,Regional,Moderately differentiated; Grade II,White,85+ years,C50.4-Upper-outer quadrant of breast,014,Surgery performed,852,Malignant,1,1,1,Right - origin of primary,Positive,Positive,IIA,1.5,2,0,1
414514,Localized,Well differentiated; Grade I,White,75-79 years,C50.5-Lower-outer quadrant of breast,016,Surgery performed,850,Malignant,0,11,2,Left - origin of primary,Positive,Positive,I,1.5,0,0,-1
327832,Localized,Poorly differentiated; Grade III,Asian or Pacific Islander,45-49 years,C50.4-Upper-outer quadrant of breast,015,Surgery performed,850,Malignant,0,27,2,Right - origin of primary,Positive,Positive,I,1.5,0,0,-1
41036,Localized,Moderately differentiated; Grade II,White,40-44 years,C50.4-Upper-outer quadrant of breast,040,Surgery performed,850,Malignant,0,3,1,Right - origin of primary,Positive,Positive,IIA,3,0,0,1

## Split

In [62]:
np.random.seed(42)
from sklearn.model_selection import train_test_split
train, test = train_test_split(d_shuffle, test_size=0.2, random_state=42)
#y = d_shuffle[['Survival months']]
#x = d_shuffle.drop(columns='Survival months')
#print(y.shape, x.shape)

In [63]:
print(train.shape, test.shape)

(257608, 20) (64402, 20)

In [64]:
test

,Summary stage 2000 (1998+),Grade,"Race recode (W, B, AI, API)",Age recode with <1 year olds,Primary Site - labeled,CS tumor size (2004-2015),Reason no cancer-directed surgery,Histologic Type ICD-O-3,Behavior code ICD-O-3,Regional nodes positive (1988+),Regional nodes examined (1988+),Total number of in situ/malignant tumors for patient,Laterality,ER Status Recode Breast Cancer (1990+),PR Status Recode Breast Cancer (1990+),Breast - Adjusted AJCC 6th Stage (1988-2015),Breast - Adjusted AJCC 6th T (1988-2015),Breast - Adjusted AJCC 6th N (1988-2015),Breast - Adjusted AJCC 6th M (1988-2015),Survival months
300957,Localized,Moderately differentiated; Grade II,White,60-64 years,C50.8-Overlapping lesion of breast,035,Surgery performed,902,Malignant,0,15,1,Right - origin of primary,Unknown,Unknown,IIA,3,0,0,1
58456,Localized,Poorly differentiated; Grade III,White,60-64 years,"C50.9-Breast, NOS",011,Surgery performed,850,Malignant,0,1,1,Right - origin of primary,Positive,Positive,I,1.5,0,0,1
429774,Regional,Moderately differentiated; Grade II,Asian or Pacific Islander,40-44 years,C50.1-Central portion of breast,030,Surgery performed,850,Malignant,8,10,2,Right - origin of primary,Negative,Negative,IIIA,3,6.5,0,1
226774,Localized,Moderately differentiated; Grade II,White,70-74 years,C50.8-Overlapping lesion of breast,009,Surgery performed,850,Malignant,0,1,01,Right - origin of primary,Positive,Positive,I,0.75,0,0,-1
194850,Regional,Moderately differentiated; Grade II,White,45-49 years,C50.4-Upper-outer quadrant of breast,025,Surgery performed,852,Malignant,1,19,3,Right - origin of primary,Positive,Positive,IIB,3,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204005,Regional,Poorly differentiated; Grade III,Asian or Pacific Islander,45-49 years,C50.4-Upper-outer quadrant of breast,045,Surgery performed,852,Malignant,1,2,1,Left - origin of primary,Positive,Positive,IIIB,7,2,0,1
77221,Localized,Poorly differentiated; Grade III,White,65-69 years,C50.4-Upper-outer quadrant of breast,032,Surgery performed,850,Malignant,0,1,1,Left - origin of primary,Positive,Negative,IIA,3,0,0,1
48914,Localized,Well differentiated; Grade I,White,80-84 years,"C50.9-Breast, NOS",008,Surgery performed,850,Malignant,0,1,1,Right - origin of primary,Positive,Positive,I,0.75,0,0,-1
318688,Localized,Well differentiated; Grade I,White,45-49 years,C50.4-Upper-outer quadrant of breast,004,Surgery performed,821,Malignant,0,4,1,Right - origin of primary,Positive,Positive,I,0.25,0,0,1
73757,Localized,Poorly differentiated; Grade III,White,60-64 years,C50.4-Upper-outer quadrant of breast,029,Surgery performed,850,Malignant,0,6,1,Right - origin of primary,Positive,Positive,IIA,3,0,0,-1

In [67]:
print(test['Survival months'].value_counts())
print(train['Survival months'].value_counts())

-1    32221
 1    32181
Name: Survival months, dtype: int64
 1    128824
-1    128784
Name: Survival months, dtype: int64

# Preprocessing

### Refactor

so..... i dont think you need to hm. scale after you encode?????? or just dont do encoding and do one hot encoding for all of them

actually i think you can just try both of them and see which preprocessing turns out to be better 12/16/20

In [68]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [69]:
class Preprocessing:
    from sklearn.preprocessing import OrdinalEncoder
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import OneHotEncoder
    from sklearn.preprocessing import MinMaxScaler
    from sklearn.compose import ColumnTransformer
    from sklearn.impute import SimpleImputer
        
    def __init__(self, data):
        self.data = data
    
    def preprocess_all(self, scale_var, encode_var, hot_var):
        num = self.num_pipeline()
        encode = self.encode_scale_pipeline()
        one_hot = self.one_hot_pipeline()
        
        pipeline = ColumnTransformer([
        ('one_hot', one_hot, hot_var),
        ('encode', encode, encode_var),
        ('num', num, scale_var)
        ], remainder='passthrough')
        
        data_final = pipeline.fit_transform(self.data)
        return data_final
    
    def encode_scale_pipeline(self):
        encode_pipeline = Pipeline([
            ('encode', OrdinalEncoder()),
            ('scale', MinMaxScaler())
        ])
        return encode_pipeline
    
    def encode_pipeline(self):
        encode_pipeline = Pipeline([
            ('encode', OrdinalEncoder())
        ])
        return encode_pipeline    
    
    def num_pipeline(self):
        num_pipeline = Pipeline([
            ('imputer', SimpleImputer(strategy="median")),
            ('minmax', MinMaxScaler())
        ])
        return num_pipeline
    
    def one_hot_pipeline(self):
        one_hot_pipeline = Pipeline([
            ('cat_one_hot', OneHotEncoder())
        ])
        return one_hot_pipeline

In [81]:
scale = ['CS tumor size (2004-2015)',  'Regional nodes positive (1988+)',  'Regional nodes examined (1988+)',  'Total number of in situ/malignant tumors for patient', 
         'Breast - Adjusted AJCC 6th T (1988-2015)', 'Breast - Adjusted AJCC 6th N (1988-2015)', 'Breast - Adjusted AJCC 6th M (1988-2015)']
#hot =  ['Laterality', 'Grade']
hot=[]
encode = ['Summary stage 2000 (1998+)', 'Grade',  'Race recode (W, B, AI, API)',  'Age recode with <1 year olds',  'Primary Site - labeled', 
           'Reason no cancer-directed surgery',  'Histologic Type ICD-O-3',  'Behavior code ICD-O-3',  'Laterality',
          'ER Status Recode Breast Cancer (1990+)', 'PR Status Recode Breast Cancer (1990+)', 'Breast - Adjusted AJCC 6th Stage (1988-2015)']

In [82]:
preprocess_1 = Preprocessing(train)
train_final = preprocess_1.preprocess_all(scale, encode, hot)

In [83]:
train_f = pd.DataFrame(train_final)

In [87]:
train_f

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.666667,0.000000,1.00,0.4375,0.500,1.0,0.756757,1.0,0.25,0.666667,0.666667,0.166667,0.007085,0.000000,0.000000,0.000000,0.083333,0.0,0.0,1.0
1,0.666667,1.000000,1.00,0.8125,0.875,1.0,0.702703,1.0,1.00,0.666667,0.666667,0.166667,0.009109,0.000000,0.011236,0.000000,0.083333,0.0,0.0,1.0
2,1.000000,0.333333,1.00,0.6250,1.000,1.0,0.756757,1.0,1.00,0.666667,0.666667,0.500000,0.029352,0.010101,0.022472,0.000000,0.333333,0.2,0.0,-1.0
3,0.666667,1.000000,1.00,0.6875,0.500,1.0,0.756757,1.0,0.25,0.666667,0.666667,0.333333,0.031377,0.000000,0.000000,0.000000,0.333333,0.0,0.0,1.0
4,0.666667,0.333333,1.00,0.3750,0.500,1.0,0.756757,1.0,1.00,0.333333,0.333333,0.166667,0.017206,0.000000,0.000000,0.000000,0.166667,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257603,0.666667,1.000000,0.50,0.5625,0.500,1.0,0.810811,1.0,0.25,0.666667,0.666667,0.166667,0.014170,0.000000,0.022472,0.000000,0.166667,0.0,0.0,-1.0
257604,0.666667,0.333333,1.00,0.5625,0.375,1.0,0.756757,1.0,1.00,0.333333,0.333333,0.166667,0.011134,0.000000,0.022472,0.000000,0.166667,0.0,0.0,1.0
257605,0.666667,0.333333,1.00,0.3750,0.500,1.0,0.756757,1.0,1.00,0.666667,0.666667,0.166667,0.014170,0.000000,0.033708,0.000000,0.166667,0.0,0.0,1.0
257606,0.666667,0.333333,0.25,0.4375,0.375,1.0,0.324324,1.0,0.25,0.666667,0.333333,0.166667,0.014170,0.000000,0.033708,0.000000,0.166667,0.0,0.0,1.0
257607,0.666667,1.000000,1.00,0.5625,0.875,1.0,0.810811,1.0,1.00,0.666667,0.666667,0.166667,0.012146,0.000000,0.000000,0.083333,0.166667,0.0,0.0,1.0

In [85]:
preprocess_2 = Preprocessing(test)
test_final = preprocess_2.preprocess_all(scale, encode, hot)
test_f = pd.DataFrame(test_final)
test_f

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.666667,0.000000,1.00,0.642857,0.875,1.0,1.00000,1.0,1.00,1.000000,1.000000,0.333333,0.034413,0.000000,0.157303,0.000000,0.333333,0.00,0.0,1.0
1,0.666667,0.333333,1.00,0.642857,1.000,1.0,0.71875,1.0,1.00,0.666667,0.666667,0.166667,0.010121,0.000000,0.000000,0.000000,0.166667,0.00,0.0,1.0
2,1.000000,0.000000,0.25,0.357143,0.125,1.0,0.71875,1.0,1.00,0.333333,0.333333,0.666667,0.029352,0.080808,0.101124,0.142857,0.333333,0.65,0.0,1.0
3,0.666667,0.000000,1.00,0.785714,0.875,1.0,0.71875,1.0,1.00,0.666667,0.666667,0.166667,0.008097,0.000000,0.000000,0.000000,0.083333,0.00,0.0,-1.0
4,1.000000,0.000000,1.00,0.428571,0.500,1.0,0.78125,1.0,1.00,0.666667,0.666667,0.500000,0.024291,0.010101,0.202247,0.285714,0.333333,0.20,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64397,1.000000,0.333333,0.25,0.428571,0.500,1.0,0.78125,1.0,0.25,0.666667,0.666667,0.833333,0.044534,0.010101,0.011236,0.000000,0.777778,0.20,0.0,1.0
64398,0.666667,0.333333,1.00,0.714286,0.500,1.0,0.71875,1.0,0.25,0.666667,0.333333,0.333333,0.031377,0.000000,0.000000,0.000000,0.333333,0.00,0.0,1.0
64399,0.666667,1.000000,1.00,0.928571,1.000,1.0,0.71875,1.0,1.00,0.666667,0.666667,0.166667,0.007085,0.000000,0.000000,0.000000,0.083333,0.00,0.0,-1.0
64400,0.666667,1.000000,1.00,0.428571,0.500,1.0,0.34375,1.0,1.00,0.666667,0.666667,0.166667,0.003036,0.000000,0.033708,0.000000,0.027778,0.00,0.0,1.0
64401,0.666667,0.333333,1.00,0.642857,0.500,1.0,0.71875,1.0,1.00,0.666667,0.666667,0.333333,0.028340,0.000000,0.056180,0.000000,0.333333,0.00,0.0,-1.0

data-2.txt has 448215 rows × 15 columns
data-3.txt has 439719 rows and 19 cols

data-4.txt has 257608 x 19 for train, 64402 x 19 for test

# WRITE TO TEXT FILE

In [88]:
train_f.to_csv('/cluster/2021mqian/snr research/recurrence_my_project/data-4-train.txt', sep=',', index=False, header=True)

In [89]:
test_f.to_csv('/cluster/2021mqian/snr research/recurrence_my_project/data-4-test.txt', sep=',', index=False, header=True)

# Training (old)

In [152]:
target = pd.DataFrame(target_1.to_numpy(), columns=['Survival months'])
target

        Survival months
0                     1
1                     1
2                     1
3                     1
4                     1
...                 ...
448210                1
448211                1
448212                1
448213                1
448214                1

[448215 rows x 1 columns]

In [153]:
data_f

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.333333,0.666667,1.00,1.0000,1.000,1.0,0.611111,0.0,1.00,0.333333,0.333333,0.017206,0.000000,0.000000,0.166667
1,0.333333,0.666667,1.00,0.6875,0.125,1.0,0.648148,0.0,0.25,0.333333,0.333333,0.024291,0.000000,0.000000,0.083333
2,0.333333,0.333333,0.25,0.6250,0.500,1.0,0.648148,0.0,1.00,0.333333,0.333333,0.029352,0.000000,0.000000,0.166667
3,0.333333,0.666667,1.00,0.8750,0.500,1.0,0.611111,0.0,0.25,0.333333,0.333333,0.004049,0.000000,0.011236,0.166667
4,0.333333,0.000000,0.25,0.6875,0.250,1.0,0.648148,0.0,0.25,0.666667,0.666667,0.032389,0.000000,0.011236,0.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448210,1.000000,0.000000,1.00,0.5625,0.500,1.0,0.648148,1.0,0.25,0.666667,0.666667,0.011134,0.101010,0.258427,0.000000
448211,0.666667,0.000000,1.00,0.7500,0.875,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.011134,0.000000,0.011236,0.000000
448212,0.666667,0.000000,1.00,0.3125,0.250,1.0,0.611111,1.0,1.00,0.666667,0.666667,0.014170,0.000000,0.033708,0.000000
448213,0.666667,1.000000,1.00,0.6250,0.250,1.0,0.648148,1.0,0.25,0.666667,0.333333,0.019231,0.000000,0.011236,0.000000
448214,1.000000,0.333333,1.00,0.6250,0.875,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.034413,0.121212,0.134831,0.000000

In [154]:
data_all = pd.concat([data_f, target], axis=1)
data_all

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Survival months
0,0.333333,0.666667,1.00,1.0000,1.000,1.0,0.611111,0.0,1.00,0.333333,0.333333,0.017206,0.000000,0.000000,0.166667,1
1,0.333333,0.666667,1.00,0.6875,0.125,1.0,0.648148,0.0,0.25,0.333333,0.333333,0.024291,0.000000,0.000000,0.083333,1
2,0.333333,0.333333,0.25,0.6250,0.500,1.0,0.648148,0.0,1.00,0.333333,0.333333,0.029352,0.000000,0.000000,0.166667,1
3,0.333333,0.666667,1.00,0.8750,0.500,1.0,0.611111,0.0,0.25,0.333333,0.333333,0.004049,0.000000,0.011236,0.166667,1
4,0.333333,0.000000,0.25,0.6875,0.250,1.0,0.648148,0.0,0.25,0.666667,0.666667,0.032389,0.000000,0.011236,0.083333,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448210,1.000000,0.000000,1.00,0.5625,0.500,1.0,0.648148,1.0,0.25,0.666667,0.666667,0.011134,0.101010,0.258427,0.000000,1
448211,0.666667,0.000000,1.00,0.7500,0.875,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.011134,0.000000,0.011236,0.000000,1
448212,0.666667,0.000000,1.00,0.3125,0.250,1.0,0.611111,1.0,1.00,0.666667,0.666667,0.014170,0.000000,0.033708,0.000000,1
448213,0.666667,1.000000,1.00,0.6250,0.250,1.0,0.648148,1.0,0.25,0.666667,0.333333,0.019231,0.000000,0.011236,0.000000,1
448214,1.000000,0.333333,1.00,0.6250,0.875,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.034413,0.121212,0.134831,0.000000,1

Resampling --> having the same number of survived and did not survive

In [155]:
data_all['Survival months'].value_counts()

 1    281919
-1    166296
Name: Survival months, dtype: int64

In [156]:
low = data_all[['Survival months']].value_counts().min()
low

166296

Choosing the number of random samples that have (data-2 166296)  (data-3 161005) (data-1 171866) for the survived (1) cases

In [157]:
samples = data_all[data_all['Survival months'] == 1].index.values
index_range = range(samples.shape[0])
indexes = np.random.choice(index_range, size=low, replace=False)
subsample =  samples[indexes].tolist()
d_1 = data_all.loc[subsample, :]

In [158]:
d_1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Survival months
60822,0.666667,0.333333,1.0,0.3750,0.625,1.0,0.611111,1.0,0.25,0.333333,0.333333,0.026316,0.000000,0.011236,0.000000,1
152243,1.000000,0.333333,1.0,0.8750,0.125,1.0,0.611111,1.0,0.25,0.666667,0.333333,0.030364,0.010101,0.146067,0.000000,1
71082,0.666667,0.000000,1.0,0.7500,1.000,1.0,0.648148,1.0,1.00,0.666667,0.666667,0.011134,0.000000,0.000000,0.083333,1
309807,0.666667,1.000000,1.0,0.7500,0.875,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.013158,0.000000,0.011236,0.000000,1
283555,0.666667,1.000000,1.0,0.8750,0.500,1.0,0.611111,1.0,1.00,0.666667,0.666667,0.006073,0.000000,0.044944,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425004,0.666667,0.000000,1.0,0.6875,0.500,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.006073,0.000000,0.022472,0.000000,1
311752,0.666667,1.000000,1.0,0.8750,0.875,1.0,0.648148,1.0,0.25,0.333333,0.333333,0.008097,0.000000,0.044944,0.000000,1
415387,0.666667,0.333333,1.0,0.7500,0.250,1.0,0.611111,1.0,1.00,0.666667,0.666667,0.009109,0.000000,0.011236,0.000000,1
254028,0.666667,0.000000,1.0,0.6875,0.875,1.0,0.648148,1.0,0.25,0.666667,0.666667,0.055668,0.000000,0.022472,0.000000,1
245883,1.000000,0.333333,1.0,0.6875,0.625,1.0,0.611111,1.0,0.25,0.666667,0.333333,0.024291,0.010101,0.202247,0.000000,1

In [159]:
samples_0 = data_all[data_all['Survival months'] == -1].index.values
d_0 = data_all.loc[samples_0, :]

In [160]:
d_0

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Survival months
6,0.333333,0.000000,0.25,0.6875,0.500,1.0,0.648148,0.0,0.25,0.666667,0.666667,0.007085,0.000000,0.000000,0.083333,-1
17,0.333333,0.333333,0.50,0.5625,0.500,1.0,0.648148,0.0,1.00,0.666667,0.666667,0.024291,0.000000,0.011236,0.166667,-1
18,0.333333,0.333333,0.25,0.6250,0.875,1.0,0.611111,0.0,0.25,0.666667,0.666667,0.019231,0.000000,0.000000,0.083333,-1
24,0.333333,0.000000,0.50,0.6250,1.000,1.0,0.648148,0.0,1.00,0.666667,0.666667,0.049595,0.000000,0.011236,0.083333,-1
33,0.333333,0.000000,1.00,0.4375,0.250,1.0,0.611111,0.0,1.00,0.666667,0.666667,0.017206,0.000000,0.011236,0.083333,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448173,0.666667,0.333333,1.00,0.9375,0.500,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.016194,0.000000,0.056180,0.000000,-1
448178,1.000000,0.000000,0.25,0.5625,0.125,1.0,0.611111,1.0,1.00,0.666667,0.666667,0.039474,0.050505,0.056180,0.000000,-1
448183,0.000000,0.000000,1.00,0.5000,0.500,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.009109,0.000000,0.123596,0.000000,-1
448190,0.666667,0.000000,0.25,0.8125,0.875,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.007085,0.000000,0.011236,0.000000,-1
448200,0.666667,0.000000,1.00,0.5000,1.000,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.014170,0.000000,0.044944,0.000000,-1

In [161]:
d_final = pd.concat([d_1, d_0])

In [162]:
d_final[['Survival months']].value_counts()

Survival months
 1                 166296
-1                 166296
dtype: int64

In [163]:
d_final

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Survival months
60822,0.666667,0.333333,1.00,0.3750,0.625,1.0,0.611111,1.0,0.25,0.333333,0.333333,0.026316,0.000000,0.011236,0.000000,1
152243,1.000000,0.333333,1.00,0.8750,0.125,1.0,0.611111,1.0,0.25,0.666667,0.333333,0.030364,0.010101,0.146067,0.000000,1
71082,0.666667,0.000000,1.00,0.7500,1.000,1.0,0.648148,1.0,1.00,0.666667,0.666667,0.011134,0.000000,0.000000,0.083333,1
309807,0.666667,1.000000,1.00,0.7500,0.875,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.013158,0.000000,0.011236,0.000000,1
283555,0.666667,1.000000,1.00,0.8750,0.500,1.0,0.611111,1.0,1.00,0.666667,0.666667,0.006073,0.000000,0.044944,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448173,0.666667,0.333333,1.00,0.9375,0.500,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.016194,0.000000,0.056180,0.000000,-1
448178,1.000000,0.000000,0.25,0.5625,0.125,1.0,0.611111,1.0,1.00,0.666667,0.666667,0.039474,0.050505,0.056180,0.000000,-1
448183,0.000000,0.000000,1.00,0.5000,0.500,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.009109,0.000000,0.123596,0.000000,-1
448190,0.666667,0.000000,0.25,0.8125,0.875,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.007085,0.000000,0.011236,0.000000,-1
448200,0.666667,0.000000,1.00,0.5000,1.000,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.014170,0.000000,0.044944,0.000000,-1

In [164]:
d_shuffle = d_final.sample(frac=1)

In [165]:
d_shuffle

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Survival months
335422,0.666667,0.333333,0.25,0.4375,0.500,1.0,0.611111,1.0,1.00,0.333333,0.333333,0.011134,0.000000,0.022472,0.083333,1
421787,1.000000,0.333333,1.00,0.6875,1.000,1.0,0.611111,1.0,1.00,0.666667,0.666667,0.033401,0.010101,0.056180,0.000000,1
162238,0.666667,0.000000,1.00,0.6875,0.250,1.0,0.648148,1.0,0.25,0.666667,0.666667,0.018219,0.000000,0.022472,0.000000,1
79290,0.666667,0.000000,1.00,0.6250,1.000,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.008097,0.000000,0.000000,0.000000,-1
258253,1.000000,0.333333,1.00,0.6875,0.125,1.0,0.648148,1.0,0.25,0.333333,0.333333,0.011134,0.010101,0.382022,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420594,0.666667,0.000000,1.00,0.5000,0.375,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.010121,0.000000,0.022472,0.000000,1
424927,0.666667,0.333333,1.00,0.6250,0.875,1.0,0.611111,1.0,0.25,0.333333,0.333333,0.019231,0.000000,0.089888,0.000000,1
429924,1.000000,0.000000,1.00,0.6875,0.500,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.012146,0.010101,0.123596,0.000000,1
193406,1.000000,0.000000,1.00,0.7500,0.500,1.0,0.648148,1.0,0.25,0.666667,0.666667,0.024291,0.020202,0.280899,0.000000,1
69038,1.000000,1.000000,1.00,0.9375,0.500,1.0,0.611111,1.0,0.25,0.666667,0.666667,0.008097,0.040404,0.067416,0.000000,-1